#!/bin/bash


smctl kp ls ; echo ; read -p "Keypair Alias: " KP_ALIAS
###################################################################################################################
./helper-jar-helloworld
SRC_JAR="hello.jar"
SIGNING_DIR="${SIGNING_DIR:-$HOME/signing}"
###################################################################################################################
smctl certificate download --keypair-alias=$KP_ALIAS --issuer-first --chain -n ${KP_ALIAS}.crt # >/dev/null 2>&1

jarsigner -verbose -keystore NONE -storetype DIGICERT -storepass changeit \
    -J-Djava.class.path="$SIGNING_DIR/digicert-jce-1.0.jar:$SIGNING_DIR/bcprov-jdk18on-1.77.jar" \
    -providerClass com.digicert.jce.Provider -certchain ${KP_ALIAS}.crt -sigalg SHA256withRSA \
    -tsa http://timestamp.digicert.com -signedjar src/SIGNED_$SRC_JAR src/$SRC_JAR $KP_ALIAS

###################################################################################################################
cd src ; unzip SIGNED_hello.jar ; cat META-INF/*.SF ; find . -not -name "*.jar" -not -path "." -delete ; cd ..
rm *.crt
